### ISSUE TITLE
Include description of Meetup 8, 9 and 10.

### ISSUE THREAD

**Issue by kaflesudip** [PythonNepal/pythonnepal.github.io#2]
Past meetup page contains info about meetup 1-7 only.

**Comment by studenton** [comment]
@kaflesudip Where can I get the description?

**Comment by kaflesudip** [comment]
@amitness Description can be found on meetup page - https://www.meetup.com/PythonNepal/ and on [11 meetup]( https://www.facebook.com/events/1708821879409885/?active_tab=discussion&__xt__=33.%7B%22logging_data%22%3A%7B%22profile_id%22%3A1708821879409885%2C%22event_type%22%3A%22clicked_view_event_posts%22%2C%22impression_info%22%3A%22eyJmIjp7Iml0ZW1fY291bnQiOiIwIn19%22%2C%22surface%22%3A%22www_events_permalink%22%2C%22interacted_story_type%22%3A%221058178634193603%22%2C%22session_id%22%3A%22a13396c9ede6e081dbf9f4a9b3ce5d51%22%7D%7D)

**Comment by amitness** [comment]
@kaflesudip  OK

**Comment by amitness** [comment]
@kaflesudip Added upto latest meetup. Please have a look. I couldn't find some slides or video so if you've them, do share here.

http://pythonnepal.org/pages/meetups.html
