### ISSUE TITLE
Make the site https ready

### ISSUE THREAD

**Issue by kaflesudip** [PythonNepal/pythonnepal.github.io#47]
Switching to https is easy for github pages. But some static resources are hard-coded with "http://pythonnepal.org...." due to which they aren't loaded.

We need to update some settings/pages where "http://" is hardcoded and replace it with "//" so that browser automatically determines the protocol.

**Comment by Aju100** [comment]
@kaflesudip  I also wanted to do and involve in it. How can I ?

**Comment by kaflesudip** [comment]
@Aju100 If you load https://pythonnepal.org, you can see that the page loads without css. The reason for this is that, we have included css from sites with http. If you view the source, you can find the following:
```
<link rel="stylesheet" href="http://pythonnepal.org/theme/css/pure.css">
<link href="http://pythonnepal.org/static/css/custom.css" rel="stylesheet">
```
We can simply convert these links to `//`. instead of "http://". We need to do this for all http links. 

You may need to edit `publishconf.py` and `pelicanconf.py`

**Comment by iampujan** [comment]
@Aju100 , this was the conversation i missed to read. I told you same. After approving, the css were not loaded as it used to be. So, i had to revert back.

**Comment by Aju100** [comment]
@iampujan  oo i got it
