### ISSUE TITLE
Make a list of Python Developers in Nepal.

### ISSUE THREAD

**Issue by kaflesudip** [PythonNepal/pythonnepal.github.io#6]
We may use spreadsheet as the database.

**Comment by amitness** [comment]
Embed it in the website itself?

**Comment by amitness** [comment]
@kaflesudip I assume most developers will be familiar with gihub. We can create a page same as companies and let them send a PR to add themselves to file similar to this: https://github.com/PythonNepal/pythonnepal.github.io/blob/source/content/pages/pythoninnepal.md

**Comment by amitness** [comment]
@kaflesudip What do you think?

**Comment by amitness** [comment]
Also, I'm adding travis to the repo so that, if the PR is merged or a commit is pushed to source branch, automatically the site is built.

**Comment by kaflesudip** [comment]
@amitness PR sounds goods. Lets add a preliminary list and also update the readme.

**Comment by amitness** [comment]
@kaflesudip Done. I've added yours and mine for now with just name and links to media. 

http://pythonnepal.org/pages/developers.html

Here's the file they need to send a PR to for adding them:
https://github.com/PythonNepal/pythonnepal.github.io/blob/source/content/pages/developers.md

Please post about it in the group.

Also, I've added instructions for adding themselves here: https://github.com/PythonNepal/pythonnepal.github.io/blob/source/README.md#contributing
